language: node_js
node_js:
  - lts/*
cache:
  yarn: true
install:
  - yarn
script:
  - yarn build
after_success:
  - cd dist
  - git init
  - git config user.name "YunYouJun"
  - git config user.email "me@yunyoujun.cn"
  - git add .
  - git commit -m "Update Valhalla"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
env:
 global:
   - GH_REF: github.com/Fantasy-Star/valhalla.git
   - secure: "l7fpnKMIZEJArTjq0cRJTvDHi9VMT5nqkp4m/Srk8N/tXMH504DZVQ2Noy5X/GXSL+vhptpPW5AJeA1Nbp3DzR3Du3fYymyWh7pvZAo/srxCn/w02f1qDl00Kvlrrp6MmAsp555byHgusPanAO4Kr5U9dmyzbaExRAd1ZE6+ZYamkkN+43r0CXrFXqP7GxoNI+OccRaCY48ogmZhnLJj4FBHAdhC27odHGlh1/Wq2DpQ4Qh3imQM6nZysofYrw7ZCzVhomf9M481YCU1mWeFw41VIcdnCeae581B1q3f3rSWOUbm5/hhFxzpb1ltcABLKrFHKtN/nWb1QuvZmI16ZONqz4Zd8CincZQ1qIwBYOa+tYOrvLxCoPh35mwy4+l3KzYlffPR8Y2I5zp1TXWETnQGJJr9sVapdVb2BHX87E7ekGOTVBOWjJ43AepIy1xqmowNyT+bd4i61v37PYBaA7wUXbQhE0gjDTCcV4HHAdMqVI3BTviAXLFKtC5vo6bZYW0MiqGIOiqbHGYXQaMUnGW/bQQpVfb9Zucld6OGbMVaBsw6430nxOfVuwaA1kno40tcWyVtJxjB4qDsD87h25HQ94oOjTYYmy+vTFngk9iKaMqIR5Ev+lK28AUDmLgMt0EIlLpYxNDHP+JnQFKy0+WFfWgwj5/nzCVj0eUGZyA="